# apt apt

# py pyt

# workflow workflow
workflow img_sd_relight

# node url
node https://github.com/cubiq/ComfyUI_IPAdapter_plus
node https://github.com/Fannovel16/comfyui_controlnet_aux
node https://github.com/ltdrdata/ComfyUI-Impact-Pack
node https://github.com/rgthree/rgthree-comfy
node https://github.com/kijai/ComfyUI-IC-Light
node https://github.com/kijai/ComfyUI-KJNodes
node https://github.com/cubiq/ComfyUI_FaceAnalysis
node https://github.com/BadCafeCode/masquerade-nodes-comfyui
node https://github.com/EllangoK/ComfyUI-post-processing-nodes
node https://github.com/jamesWalker55/comfyui-various
node https://github.com/ltdrdata/was-node-suite-comfyui
node https://github.com/M1kep/ComfyLiterals
node https://github.com/risunobushi/comfyUI_FrequencySeparation_RGB-HSV
node https://github.com/licyk/ComfyUI-HakuImg
node https://github.com/amtarr/ComfyUI-TextureAlchemy
node https://github.com/Polygoningenieur/ComfyUI-IC-Light-Video
node https://github.com/ruucm/ruucm-comfy
node https://github.com/mickmumpitz/ComfyUI-Mickmumpitz-Nodes
node https://github.com/aining2022/ComfyUI_Swwan
node https://github.com/jomakaze/ComfyUI_JomaNodes

# model name folder url
model epicrealism_naturalSinRC1VAE.safetensors diffusion_models https://huggingface.co/gitgato/EpicReal/resolve/fd2b9d09eb5dbd5fb5a0aedfb9c24c3e0196c214/epicrealism_naturalSinRC1VAE.safetensors