#!/bin/bash

# SETUP
c=$PODDY/cmd/{1:-install}

# WORKFLOWS
$c/workflow QIE_add_items
$c/workflow QIE_change_ratio
$c/workflow QIE_character_turnaround
$c/workflow QIE_clothes_2_images
$c/workflow QIE_clothes_3_images
$c/workflow QIE_clothes_one_image
$c/workflow QIE_colorize_photo
$c/workflow QIE_combine_2_images
$c/workflow QIE_combine_3_images
$c/workflow QIE_combine_4_images
$c/workflow QIE_clothes_one_image
$c/workflow QIE_colorize_photo
$c/workflow QIE_combine_2_images
$c/workflow QIE_combine_3_images
$c/workflow QIE_combine_4_images
$c/workflow QIE_inpaint
$c/workflow QIE_one_image_edit_change_ratio
$c/workflow QIE_one_image_edit
$c/workflow QIE_remove_items
$c/workflow QIE_replace_background
$c/workflow QIE_replace_character
$c/workflow QIE_replace_text
$c/workflow QIE_restore_photo

# NODES
$c/node https://github.com/rgthree/rgthree-comfy
$c/node https://github.com/city96/ComfyUI-GGUF
$c/node https://github.com/gseth/ControlAltAI-Nodes
$c/node https://github.com/lquesada/ComfyUI-Inpaint-CropAndStitch

# MODELS
$c/model qwen_image_vae.safetensors vae https://huggingface.co/Comfy-Org/Qwen-Image_ComfyUI/resolve/main/split_files/vae/qwen_image_vae.safetensors
$c/model qwen_2.5_vl_7b_fp8_scaled.safetensors text_encoders https://huggingface.co/Comfy-Org/Qwen-Image_ComfyUI/resolve/main/split_files/text_encoders/qwen_2.5_vl_7b_fp8_scaled.safetensors
$c/model Qwen_Image_Edit-Q8_0.gguf diffusion_models https://huggingface.co/QuantStack/Qwen-Image-Edit-GGUF/resolve/main/Qwen_Image_Edit-Q8_0.gguf
$c/model Qwen-Image-Edit-Lightning-8steps-V1.0.safetensors loras https://huggingface.co/lightx2v/Qwen-Image-Lightning/resolve/main/Qwen-Image-Edit-Lightning-8steps-V1.0.safetensors?download=true

