workflow QIE_add_items
workflow QIE_change_ratio
workflow QIE_character_turnaround
workflow QIE_clothes_2_images
workflow QIE_clothes_3_images
workflow QIE_clothes_one_image
workflow QIE_colorize_photo
workflow QIE_combine_2_images
workflow QIE_combine_3_images
workflow QIE_combine_4_images
workflow QIE_clothes_one_image
workflow QIE_colorize_photo
workflow QIE_combine_2_images
workflow QIE_combine_3_images
workflow QIE_combine_4_images
workflow QIE_inpaint
workflow QIE_one_image_edit_change_ratio
workflow QIE_one_image_edit
workflow QIE_remove_items
workflow QIE_replace_background
workflow QIE_replace_character
workflow QIE_replace_text
workflow QIE_restore_photo
#node https://github.com/rgthree/rgthree-comfy
#node https://github.com/city96/ComfyUI-GGUF
#node https://github.com/gseth/ControlAltAI-Nodes
#node https://github.com/lquesada/ComfyUI-Inpaint-CropAndStitch
model qwen_image_vae.safetensors vae https://huggingface.co/Comfy-Org/Qwen-Image_ComfyUI/resolve/main/split_files/vae/qwen_image_vae.safetensors
model qwen_2.5_vl_7b_fp8_scaled.safetensors text_encoders https://huggingface.co/Comfy-Org/Qwen-Image_ComfyUI/resolve/main/split_files/text_encoders/qwen_2.5_vl_7b_fp8_scaled.safetensors
model Qwen_Image_Edit-Q8_0.gguf diffusion_models https://huggingface.co/QuantStack/Qwen-Image-Edit-GGUF/resolve/main/Qwen_Image_Edit-Q8_0.gguf
model Qwen-Image-Edit-Lightning-8steps-V1.0.safetensors loras https://huggingface.co/lightx2v/Qwen-Image-Lightning/resolve/main/Qwen-Image-Edit-Lightning-8steps-V1.0.safetensors?download=true

