workflow sdxl_hair_transfer
#node https://github.com/a-und-b/ComfyUI_LoRA_from_URL
#node https://github.com/lldacing/ComfyUI_StableHair_ll
#node https://github.com/cubiq/ComfyUI_essentials
#node https://github.com/yolain/ComfyUI-Easy-Use
#node https://github.com/a-und-b/ComfyUI_LoRA_from_URL
model realisticVisionV60B1_v51VAE.safetensors diffusion_models https://huggingface.co/khaimd123/realisticVisionV60B1_v51VAE/resolve/5314c8485d833085571162c6bd3664eabdc6b25f/realisticVisionV60B1_v51VAE.safetensors
