#!/bin/bash

# SETUP
c=$PODDY/cmd/${1:-install}

# WORKFLOWS
$c/workflow svg_generate_vector_designs
$c/workflow svg_image _to_vector_silhouette
$c/workflow svg_image_vector_variation
$c/workflow svg_img_to_svg

# NODES
$c/node https://github.com/city96/ComfyUI-GGUF
$c/node https://github.com/rgthree/rgthree-comfy
$c/node https://github.com/Yanick112/ComfyUI-ToSVG
$c/node https://github.com/kael558/ComfyUI-GGUF-FantasyTalking

# MODELS
$c/model flux1-dev-Q8_0.gguf diffusion_models https://huggingface.co/YarvixPA/FLUX.1-Fill-dev-gguf/resolve/main/flux1-fill-dev-Q8_0.gguf?download=true
$c/model t5-v1_1-xxl-encoder-Q8_0.gguf clip https://huggingface.co/city96/t5-v1_1-xxl-encoder-gguf/resolve/main/t5-v1_1-xxl-encoder-Q8_0.gguf?download=true
$c/model clip_l.safetensors clip https://huggingface.co/city96/t5-v1_1-xxl-encoder-gguf/resolve/main/t5-v1_1-xxl-encoder-Q8_0.gguf?download=true
$c/model ae.safetensor vae https://huggingface.co/Comfy-Org/Lumina_Image_2.0_Repackaged/resolve/main/split_files/vae/ae.safetensors?download=true
$c/model svg_style.safetensors loras https://huggingface.co/Pixaroma/flux-kontext-loras/resolve/main/svg_style.safetensors?download=true
