#!/bin/bash

# SETUP
c=$PODDY/cmd/{1:-install}

# WORKFLOWS
$c/workflow wan_2_2_gguf_lora

# NODES
$c/node https://github.com/rgthree/rgthree-comfy
$c/node https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite
$c/node https://github.com/kijai/ComfyUI-WanVideoWrapper
$c/node https://github.com/city96/ComfyUI-GGUF

# MODELS
$c/model wan2.2_i2v_A14b_high_noise_lightx2v_4step-Q6_K.gguf diffusion_models https://huggingface.co/jayn7/WAN2.2-I2V_A14B-DISTILL-LIGHTX2V-4STEP-GGUF/resolve/main/high_noise/wan2.2_i2v_A14b_high_noise_lightx2v_4step-Q6_K.gguf?download=true
$c/model wan2.2_i2v_A14b_low_noise_lightx2v_4step-Q6_K.gguf diffusion_models https://huggingface.co/jayn7/WAN2.2-I2V_A14B-DISTILL-LIGHTX2V-4STEP-GGUF/resolve/main/high_noise/wan2.2_i2v_A14b_high_noise_lightx2v_4step-Q6_K.gguf?download=true
$c/model umt5_xxl_fp8_e4m3fn_scaled.safetensors text_encoders https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/text_encoders/umt5_xxl_fp8_e4m3fn_scaled.safetensors?download=true
$c/model wan_2.1_vae.safetensors vae https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/vae/wan_2.1_vae.safetensors?download=true
